# Generated by Django 5.1.7 on 2025-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plainte',
            old_name='date_soumission',
            new_name='date_creation',
        ),
        migrations.AlterField(
            model_name='plainte',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
